// organization
export const ORGANIZATION_LIST_REQUEST = 'ORGANIZATION_LIST_REQUEST'
export const ORGANIZATION_LIST_SUCCESS = 'ORGANIZATION_LIST_SUCCESS'
export const ORGANIZATION_LIST_FAILURE = 'ORGANIZATION_LIST_FAILURE'

export const ORGANIZATION_CREATE_REQUEST = 'ORGANIZATION_CREATE_REQUEST'
export const ORGANIZATION_CREATE_SUCCESS = 'ORGANIZATION_CREATE_SUCCESS'
export const ORGANIZATION_CREATE_FAILURE = 'ORGANIZATION_CREATE_FAILURE'

export const ORGANIZATION_UPDATE_REQUEST = 'ORGANIZATION_UPDATE_REQUEST'
export const ORGANIZATION_UPDATE_SUCCESS = 'ORGANIZATION_UPDATE_SUCCESS'
export const ORGANIZATION_UPDATE_FAILURE = 'ORGANIZATION_UPDATE_FAILURE'

export const ORGANIZATION_DELETE_REQUEST = 'ORGANIZATION_DELETE_REQUEST'
export const ORGANIZATION_DELETE_SUCCESS = 'ORGANIZATION_DELETE_SUCCESS'
export const ORGANIZATION_DELETE_FAILURE = 'ORGANIZATION_DELETE_FAILURE'

export const ORGANIZATION_STATUS_REQUEST = 'ORGANIZATION_STATUS_REQUEST'
export const ORGANIZATION_STATUS_SUCCESS = 'ORGANIZATION_STATUS_SUCCESS'
export const ORGANIZATION_STATUS_FAILURE = 'ORGANIZATION_STATUS_FAILURE'

export const ORGANIZATION_EDITOR_OPEN = 'ORGANIZATION_EDITOR_OPEN'
export const ORGANIZATION_EDITOR_CLOSE = 'ORGANIZATION_EDITOR_CLOSE'

// department
export const DEPARTMENT_LIST_REQUEST = 'DEPARTMENT_LIST_REQUEST'
export const DEPARTMENT_LIST_SUCCESS = 'DEPARTMENT_LIST_SUCCESS'
export const DEPARTMENT_LIST_FAILURE = 'DEPARTMENT_LIST_FAILURE'

export const DEPARTMENT_CREATE_REQUEST = 'DEPARTMENT_CREATE_REQUEST'
export const DEPARTMENT_CREATE_SUCCESS = 'DEPARTMENT_CREATE_SUCCESS'
export const DEPARTMENT_CREATE_FAILURE = 'DEPARTMENT_CREATE_FAILURE'

export const DEPARTMENT_UPDATE_REQUEST = 'DEPARTMENT_UPDATE_REQUEST'
export const DEPARTMENT_UPDATE_SUCCESS = 'DEPARTMENT_UPDATE_SUCCESS'
export const DEPARTMENT_UPDATE_FAILURE = 'DEPARTMENT_UPDATE_FAILURE'

export const DEPARTMENT_DELETE_REQUEST = 'DEPARTMENT_DELETE_REQUEST'
export const DEPARTMENT_DELETE_SUCCESS = 'DEPARTMENT_DELETE_SUCCESS'
export const DEPARTMENT_DELETE_FAILURE = 'DEPARTMENT_DELETE_FAILURE'

export const DEPARTMENT_STATUS_REQUEST = 'DEPARTMENT_STATUS_REQUEST'
export const DEPARTMENT_STATUS_SUCCESS = 'DEPARTMENT_STATUS_SUCCESS'
export const DEPARTMENT_STATUS_FAILURE = 'DEPARTMENT_STATUS_FAILURE'

export const DEPARTMENT_EDITOR_OPEN = 'DEPARTMENT_EDITOR_OPEN'
export const DEPARTMENT_EDITOR_CLOSE = 'DEPARTMENT_EDITOR_CLOSE'

// position
export const POSITION_LIST_REQUEST = 'POSITION_LIST_REQUEST'
export const POSITION_LIST_SUCCESS = 'POSITION_LIST_SUCCESS'
export const POSITION_LIST_FAILURE = 'POSITION_LIST_FAILURE'

export const POSITION_CREATE_REQUEST = 'POSITION_CREATE_REQUEST'
export const POSITION_CREATE_SUCCESS = 'POSITION_CREATE_SUCCESS'
export const POSITION_CREATE_FAILURE = 'POSITION_CREATE_FAILURE'

export const POSITION_UPDATE_REQUEST = 'POSITION_UPDATE_REQUEST'
export const POSITION_UPDATE_SUCCESS = 'POSITION_UPDATE_SUCCESS'
export const POSITION_UPDATE_FAILURE = 'POSITION_UPDATE_FAILURE'

export const POSITION_DELETE_REQUEST = 'POSITION_DELETE_REQUEST'
export const POSITION_DELETE_SUCCESS = 'POSITION_DELETE_SUCCESS'
export const POSITION_DELETE_FAILURE = 'POSITION_DELETE_FAILURE'

export const POSITION_STATUS_REQUEST = 'POSITION_STATUS_REQUEST'
export const POSITION_STATUS_SUCCESS = 'POSITION_STATUS_SUCCESS'
export const POSITION_STATUS_FAILURE = 'POSITION_STATUS_FAILURE'

export const POSITION_EDITOR_OPEN = 'POSITION_EDITOR_OPEN'
export const POSITION_EDITOR_CLOSE = 'POSITION_EDITOR_CLOSE'

// role
export const ROLE_LIST_REQUEST = 'ROLE_LIST_REQUEST'
export const ROLE_LIST_SUCCESS = 'ROLE_LIST_SUCCESS'
export const ROLE_LIST_FAILURE = 'ROLE_LIST_FAILURE'

export const ROLE_CREATE_REQUEST = 'ROLE_CREATE_REQUEST'
export const ROLE_CREATE_SUCCESS = 'ROLE_CREATE_SUCCESS'
export const ROLE_CREATE_FAILURE = 'ROLE_CREATE_FAILURE'

export const ROLE_UPDATE_REQUEST = 'ROLE_UPDATE_REQUEST'
export const ROLE_UPDATE_SUCCESS = 'ROLE_UPDATE_SUCCESS'
export const ROLE_UPDATE_FAILURE = 'ROLE_UPDATE_FAILURE'

export const ROLE_DELETE_REQUEST = 'ROLE_DELETE_REQUEST'
export const ROLE_DELETE_SUCCESS = 'ROLE_DELETE_SUCCESS'
export const ROLE_DELETE_FAILURE = 'ROLE_DELETE_FAILURE'

export const ROLE_STATUS_REQUEST = 'ROLE_STATUS_REQUEST'
export const ROLE_STATUS_SUCCESS = 'ROLE_STATUS_SUCCESS'
export const ROLE_STATUS_FAILURE = 'ROLE_STATUS_FAILURE'

export const ROLE_EDITOR_OPEN = 'ROLE_EDITOR_OPEN'
export const ROLE_EDITOR_CLOSE = 'ROLE_EDITOR_CLOSE'