// action types
export const COUNT_PLUS = 'COUNT_PLUS'
export const COUNT_MINUS = 'COUNT_MINUS'

// organization
export const ORGANIZATION_LIST_REQUEST = 'ORGANIZATION_LIST_REQUEST'
export const ORGANIZATION_LIST_SUCCESS = 'ORGANIZATION_LIST_SUCCESS'
export const ORGANIZATION_LIST_FAILURE = 'ORGANIZATION_LIST_FAILURE'

export const ORGANIZATION_CREATE_REQUEST = 'ORGANIZATION_CREATE_REQUEST'
export const ORGANIZATION_CREATE_SUCCESS = 'ORGANIZATION_CREATE_SUCCESS'
export const ORGANIZATION_CREATE_FAILURE = 'ORGANIZATION_CREATE_FAILURE'

export const ORGANIZATION_UPDATE_REQUEST = 'ORGANIZATION_UPDATE_REQUEST'
export const ORGANIZATION_UPDATE_SUCCESS = 'ORGANIZATION_UPDATE_SUCCESS'
export const ORGANIZATION_UPDATE_FAILURE = 'ORGANIZATION_UPDATE_FAILURE'

export const ORGANIZATION_DELETE_REQUEST = 'ORGANIZATION_DELETE_REQUEST'
export const ORGANIZATION_DELETE_SUCCESS = 'ORGANIZATION_DELETE_SUCCESS'
export const ORGANIZATION_DELETE_FAILURE = 'ORGANIZATION_DELETE_FAILURE'
export const ORGANIZATION_STATUS_REQUEST = 'ORGANIZATION_STATUS_REQUEST'
export const ORGANIZATION_STATUS_SUCCESS = 'ORGANIZATION_STATUS_SUCCESS'
export const ORGANIZATION_STATUS_FAILURE = 'ORGANIZATION_STATUS_FAILURE'

export const ORGANIZATION_EDITOR_OPEN = 'ORGANIZATION_EDITOR_OPEN'
export const ORGANIZATION_EDITOR_CLOSE = 'ORGANIZATION_EDITOR_CLOSE'

// department
export const DEPARTMENT_LIST_REQUEST = 'DEPARTMENT_LIST_REQUEST'
export const DEPARTMENT_LIST_SUCCESS = 'DEPARTMENT_LIST_SUCCESS'
export const DEPARTMENT_LIST_FAILURE = 'DEPARTMENT_LIST_FAILURE'

export const DEPARTMENT_CREATE_REQUEST = 'DEPARTMENT_CREATE_REQUEST'
export const DEPARTMENT_CREATE_SUCCESS = 'DEPARTMENT_CREATE_SUCCESS'
export const DEPARTMENT_CREATE_FAILURE = 'DEPARTMENT_CREATE_FAILURE'

export const DEPARTMENT_UPDATE_REQUEST = 'DEPARTMENT_UPDATE_REQUEST'
export const DEPARTMENT_UPDATE_SUCCESS = 'DEPARTMENT_UPDATE_SUCCESS'
export const DEPARTMENT_UPDATE_FAILURE = 'DEPARTMENT_UPDATE_FAILURE'

export const DEPARTMENT_DELETE_REQUEST = 'DEPARTMENT_DELETE_REQUEST'
export const DEPARTMENT_DELETE_SUCCESS = 'DEPARTMENT_DELETE_SUCCESS'
export const DEPARTMENT_DELETE_FAILURE = 'DEPARTMENT_DELETE_FAILURE'

export const DEPARTMENT_EDITOR_OPEN = 'DEPARTMENT_EDITOR_OPEN'
export const DEPARTMENT_EDITOR_CLOSE = 'DEPARTMENT_EDITOR_CLOSE'

